# Image Publication
# =================
#
# This workflow builds and registers the python-build image with the Docker Hub.

---

name: 🌄 Imaging


# Triggers
# --------
#
# Run on any push to the Dockerfile on the main branch.

on:
    push:
        branches:
            -   main
        paths:
            -   'Dockerfile'


# Jobs
# ----
#
# What to do.

jobs:
    imaging:
        name: 🌠 Python Build Imaging
        runs-on: ubuntu-latest
        steps:
            -
                name: 💳 Docker Hub Identification
                uses: docker/login-action@v2
                with:
                    username: ${{secrets.DOCKERHUB_USERNAME}}
                    password: ${{secrets.DOCKERHUB_TOKEN}}
            -
                name: 📚 Repository Checkout
                uses: actions/checkout@v3
            -
                name: 🎰 QEMU Multiple Machine Emulation
                uses: docker/setup-qemu-action@v2
            -
                name: 🚢 Docker Buildx
                uses: docker/setup-buildx-action@v2
            -
                name: 🧱 Image Construction and Publication — user ID 500
                uses: docker/build-push-action@v3
                with:
                    context: .
                    file: Dockerfile
                    platforms: linux/amd64,linux/arm64
                    push: true
                    tags: |
                        ${{secrets.DOCKERHUB_USERNAME}}/python-build:3.10
                        ${{secrets.DOCKERHUB_USERNAME}}/python-build:latest

...
